Xlassix/dev
LighthouseWeb3/contracts pull request #11
Opened 2022-05-03 20:19 UTC by xlassix

2022-05-04 05:14 UTC, nandit123 commented on contracts/lighthouse_test.sol
> +    uint256 bundleStoreID;
what is the need for bundleStoreID ?

2022-05-04 05:14 UTC, nandit123 commented on contracts/lighthouse_test.sol
> +        Content[] memory failedUpload = new Content[](contents.length);
why to keep a track of failed and successful uploads?

2022-05-04 05:26 UTC, nandit123 commented on contracts/deposit_test/DepositManager.sol
> +uint256 public costOfStorage = (1000**3) / 50; // Byte per Dollar in these case 1gb/50$
1. default should be 1gb/5$
2. The division here may cause a problem since solidity doesnt have floating number. Example, 1gb/3$
3. Also gb -> bytes should be 1024**3 and not 1000**3

2022-05-04 05:32 UTC, nandit123 commented on contracts/deposit_test/DepositManager.sol
> +            .div(10**6);
why divide by 10**6 ? decimals of various stablecoins can vary chain to chain. For some tokens it might be 18 decimals (example, DAI on ETH chain) while for others it might be 6 decimals (example, usdt on ETH chain)

2022-05-04 05:34 UTC, nandit123 commented on contracts/deposit_test/DepositManager.sol
> +    function setWhiteListAddr(address _address, bool _status)
i dont think whitelist addresses are any use at the moment for us, so remove all related functions and variables from here and across test cases, etc.

2022-05-04 05:36 UTC, nandit123 requested changes
Changes requested

2022-05-04 06:11 UTC, xlassix commented on contracts/lighthouse_test.sol
> +    uint256 bundleStoreID;
It's a way to uniquely identify both the bundleStore request event, its corresponding bundleStore Success event and bundleStore Failed event

2022-05-04 06:19 UTC, xlassix commented on contracts/lighthouse_test.sol
> +        Content[] memory failedUpload = new Content[](contents.length);
Incase there are failures, we have a log. I wanted to run this by you. I was considering using just failed and the bundleStore event and exclude the success

2022-05-04 06:37 UTC, xlassix commented on contracts/deposit_test/DepositManager.sol
> +    function setWhiteListAddr(address _address, bool _status)
From our call yesterday, you said you wanted only approved contracts to call some of this function. Using just an owner and a manager doesn't satisfy that statement. 
Plus I modified the modifier to ensure only approved contracts and the owner can make that call. User address will be rejected

2022-05-04 10:21 UTC, nandit123 commented on contracts/lighthouse_test.sol
> +        Content[] memory failedUpload = new Content[](contents.length);
Can you describe a failure scenario?

2022-05-04 11:47 UTC, nandit123 commented on contracts/deposit_test/DepositManager.sol
>              .div(10**6);
should line 62 be deleted since you divided by decimals in line 61

2022-05-04 11:49 UTC, nandit123 commented on contracts/deposit_test/DepositManager.sol
> +    uint256 public costOfStorage = 214748365; // Byte per Dollar in these case 1gb/5$  which is eqivalent too ((1024**3) / 5)
what if cost of storage is 3$/gb , in that case 1024**3 wont be divisible by 3

2022-05-04 17:43 UTC, xlassix commented on contracts/deposit_test/DepositManager.sol
> +    uint256 public costOfStorage = 214748365; // Byte per Dollar in these case 1gb/5$  which is eqivalent too ((1024**3) / 5)
We have to either round up or round down that fraction. They are negligible since GB is in the order of 10^9

2022-05-04 18:09 UTC, xlassix commented on contracts/lighthouse_test.sol
> +        Content[] memory failedUpload = new Content[](contents.length);
For example insufficient space on one of the element of the array

2022-05-05 18:36 UTC, nandit123 commented on contracts/deposit_test/DepositManager.sol
> +            require(whiteListedAddr[msg.sender], "Account Not Whitelisted");
The second require statement won't be executed since the former one will fail so you might need to move whiteListedAddr[msg.sender] in the if statement like this - 

`if (msg.sender != owner() && !whiteListedAddr[msg.sender])`

2022-05-05 18:37 UTC, nandit123 requested changes
key logic changes

2022-05-05 18:41 UTC, nandit123 commented on contracts/lighthouse_test.sol
> +        if (failedUpload != 0) {
this should be failedCount variable

2022-05-05 18:42 UTC, nandit123 commented on contracts/deposit_test/DepositManager.sol
> +        IERC20(_coinAddress).transferFrom(wallet, address(this), _amount);ta
correct typo here, remove `ta` in the end

2022-05-05 22:48 UTC, xlassix commented on contracts/deposit_test/DepositManager.sol
> +        IERC20(_coinAddress).transferFrom(wallet, address(this), _amount);ta
Thanks

2022-05-05 22:49 UTC, xlassix commented on contracts/lighthouse_test.sol
> +        if (failedUpload != 0) {
Thanks!

2022-05-05 22:50 UTC, xlassix commented on contracts/deposit_test/DepositManager.sol
> +            require(whiteListedAddr[msg.sender], "Account Not Whitelisted");
could I get the test case that failed this?

2022-05-13 02:56 UTC, nandit123 approved these changes
lgtm, need to replace old files before pushing to mainnet

2022-05-13 02:56 UTC, merged